import type { Metadata } from "next";
import "../index.css";
import { Noto_Sans_Arabic } from "next/font/google";

/* const nunito = Nunito({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
}); */
const nunito = Noto_Sans_Arabic({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html dir="rtl" lang={"ar"} className={nunito.className}>
      <body>{children}</body>
    </html>
  );
}
